# Este workflow instala dependencias, ejecuta pruebas y realiza análisis con SonarCloud

name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Job para instalar dependencias
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Job para ejecutar pruebas
  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Run tests with tox
        run: tox

  # Job para análisis en SonarCloud
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [install-dependencies]  # SonarCloud requiere que las dependencias estén instaladas previamente
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be deshabilitados para un mejor análisis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener información de PR, si aplica
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
